-- Admins table: create if not exists with standard columns
CREATE TABLE IF NOT EXISTS admins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  api_key TEXT,
  role TEXT NOT NULL DEFAULT 'viewer' CHECK (role IN ('super_admin', 'admin', 'viewer'))
);

-- If admins already existed with different column names (e.g. "api - key"), add or rename to api_key
DO $$
BEGIN
  -- Rename "api - key" to api_key if that column exists
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'admins' AND column_name = 'api - key') THEN
    ALTER TABLE admins RENAME COLUMN "api - key" TO api_key;
  END IF;
  -- Add api_key if it still doesn't exist
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'admins' AND column_name = 'api_key') THEN
    ALTER TABLE admins ADD COLUMN api_key TEXT;
  END IF;
  -- Ensure role column exists and has check (add if missing)
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'admins' AND column_name = 'role') THEN
    ALTER TABLE admins ADD COLUMN role TEXT NOT NULL DEFAULT 'viewer';
  END IF;
END $$;

COMMENT ON TABLE admins IS 'Admin users: super_admin (full), admin (no manage admins), viewer (read-only)';

-- Ensure email has a unique index/constraint for ON CONFLICT (email)
CREATE UNIQUE INDEX IF NOT EXISTS admins_email_key ON admins (email);

-- Add admin_id to admin_logs for full audit trail
ALTER TABLE admin_logs ADD COLUMN IF NOT EXISTS admin_id BIGINT REFERENCES admins(id) ON DELETE SET NULL;
ALTER TABLE admin_logs ADD COLUMN IF NOT EXISTS admin_email TEXT;

-- Invoices: visible on user dashboard and email tracking
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS visible_to_user BOOLEAN DEFAULT true;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS email_sent_at TIMESTAMPTZ;

-- Seed one super_admin (set your own api_key after first login or via update)
INSERT INTO admins (email, api_key, role)
  VALUES ('contact.awais.ai@gmail.com', 'Lassi.0', 'super_admin')
ON CONFLICT (email) DO UPDATE SET role = EXCLUDED.role, api_key = COALESCE(EXCLUDED.api_key, admins.api_key);
