-- Email templates: store HTML and text bodies for all PostPilot admin/transactional emails.
-- Backend (template.service.js) reads from public.email_templates by key and uses subject, body_html, text_body.
--
-- If you get "trigger email_templates_updated already exists", run this once then re-run the script:
--   DROP TRIGGER IF EXISTS email_templates_updated ON public.email_templates;
--
-- Placeholders: {{userName}}, {{appName}}, {{days}}, {{expiresStr}}, {{dashboardUrl}},
-- {{invoiceNumber}}, {{amount}}, {{currency}}, {{dueStr}}, {{description}}, {{userEmail}},
-- {{joinedAt}}, {{approveUrl}}, {{reason}}, {{message}}

-- Trigger function (must exist before trigger)
CREATE OR REPLACE FUNCTION public.email_templates_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Table: matches Supabase public.email_templates schema
CREATE TABLE IF NOT EXISTS public.email_templates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  key TEXT NOT NULL,
  name TEXT NOT NULL,
  subject TEXT NOT NULL,
  body_html TEXT NOT NULL,
  text_body TEXT NULL,
  description TEXT NULL,
  created_at TIMESTAMP WITH TIME ZONE NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NULL DEFAULT now(),
  CONSTRAINT email_templates_pkey PRIMARY KEY (id),
  CONSTRAINT email_templates_key_key UNIQUE (key)
) TABLESPACE pg_default;

COMMENT ON TABLE public.email_templates IS 'Editable email templates; backend gets templates from here by key.';
COMMENT ON COLUMN public.email_templates.key IS 'Template key: approval, invoice, access_expiring, access_expired, signup_admin, ban, user_deleted, admin_note';
COMMENT ON COLUMN public.email_templates.body_html IS 'HTML content only (inserted into shared layout). Use {{placeholder}} for variables.';

-- Trigger to keep updated_at in sync (drop first so re-running this script never fails)
DROP TRIGGER IF EXISTS email_templates_updated ON public.email_templates;
DROP TRIGGER IF EXISTS email_templates_updated ON email_templates;
CREATE TRIGGER email_templates_updated
  BEFORE UPDATE ON public.email_templates
  FOR EACH ROW EXECUTE FUNCTION public.email_templates_updated_at();

-- Seed default templates (PostPilot branding: same UI as project)
INSERT INTO email_templates (key, name, subject, body_html, text_body, description) VALUES
(
  'approval',
  'User approved',
  'Your {{appName}} account has been approved',
  '<p>Hi {{userName}},</p>
<p>Your {{appName}} account has been approved. Your access is valid for <strong>{{days}} days</strong> until <strong>{{expiresStr}}</strong>.</p>
<p><a href="{{dashboardUrl}}" class="btn">Go to dashboard</a></p>
<p class="muted">Log in at your dashboard to get started.</p>',
  'Hi {{userName}},\n\nYour {{appName}} account has been approved. You have access for {{days}} days until {{expiresStr}}.\n\nLog in at {{dashboardUrl}} to get started.\n\n— {{appName}}',
  'Sent when admin approves a user. Placeholders: userName, appName, days, expiresStr, dashboardUrl'
),
(
  'invoice',
  'Invoice',
  '{{appName}} Invoice {{invoiceNumber}}',
  '<p>Hi {{userName}},</p>
<p>Please find your invoice below. Pay by the due date to avoid any interruption.</p>
<table class="invoice-table">
  <tr><th>Invoice number</th><td>{{invoiceNumber}}</td></tr>
  <tr><th>Description</th><td>{{description}}</td></tr>
  <tr><th>Due date</th><td>{{dueStr}}</td></tr>
  <tr class="amount-row"><th>Amount</th><td>{{currency}} {{amount}}</td></tr>
</table>
<p><a href="{{dashboardUrl}}" class="btn">View invoices</a></p>
<p class="muted">Thank you for using {{appName}}.</p>',
  'Hi {{userName}},\n\n{{appName}} Invoice\nInvoice #: {{invoiceNumber}}\nAmount: {{currency}} {{amount}}\nDue: {{dueStr}}\nDescription: {{description}}\n\nView invoices: {{dashboardUrl}}\n\n— {{appName}}',
  'Invoice email. Placeholders: userName, appName, invoiceNumber, description, dueStr, currency, amount, dashboardUrl'
),
(
  'access_expiring',
  'Access expiring soon',
  'Your {{appName}} access is expiring soon',
  '<p>Hi {{userName}},</p>
<p>Your {{appName}} access expires on <strong>{{expiresStr}}</strong>.</p>
<p>Contact us to renew and avoid any interruption to your account.</p>',
  'Hi {{userName}},\n\nYour {{appName}} access expires on {{expiresStr}}. Contact us to renew.\n\n— {{appName}}',
  'Reminder before access expires. Placeholders: userName, appName, expiresStr'
),
(
  'access_expired',
  'Access expired',
  'Your {{appName}} access has expired',
  '<p>Hi {{userName}},</p>
<p>Your {{appName}} access has expired.</p>
<p>Contact your admin to renew your access.</p>',
  'Hi {{userName}},\n\nYour {{appName}} access has expired. Contact admin to renew.\n\n— {{appName}}',
  'Sent when access has expired. Placeholders: userName, appName'
),
(
  'signup_admin',
  'New signup (to admin)',
  'New {{appName}} signup — {{userEmail}}',
  '<p>A new user has signed up and is awaiting approval.</p>
<table class="invoice-table">
  <tr><th>Name</th><td>{{userName}}</td></tr>
  <tr><th>Email</th><td>{{userEmail}}</td></tr>
  <tr><th>Joined</th><td>{{joinedAt}}</td></tr>
</table>
<p><a href="{{approveUrl}}" class="btn">Approve in admin panel</a></p>',
  'A new user has signed up.\n\nName: {{userName}}\nEmail: {{userEmail}}\nJoined: {{joinedAt}}\n\nApprove here: {{approveUrl}}',
  'Notification to admin. Placeholders: userName, userEmail, joinedAt, approveUrl'
),
(
  'ban',
  'User banned',
  'Your {{appName}} account has been restricted',
  '<p>Hi {{userName}},</p>
<p>Your {{appName}} account has been restricted.</p>
<p class="muted">If you have questions, please contact support.</p>',
  'Hi {{userName}},\n\nYour {{appName}} account has been restricted.\n\nContact support if you have questions.\n\n— {{appName}}',
  'Sent when admin bans a user. Placeholders: userName, appName. Optional: reason'
),
(
  'user_deleted',
  'User account deleted',
  'Your {{appName}} account has been removed',
  '<p>Hi {{userName}},</p>
<p>Your {{appName}} account has been permanently removed.</p>
<p class="muted">If this was a mistake, please contact support.</p>',
  'Hi {{userName}},\n\nYour {{appName}} account has been permanently removed.\n\n— {{appName}}',
  'Sent when super_admin deletes a user (optional). Placeholders: userName, appName'
),
(
  'admin_note',
  'Admin note / message',
  'Message from {{appName}}',
  '<p>Hi {{userName}},</p>
<p>{{message}}</p>
<p><a href="{{dashboardUrl}}" class="btn">Go to dashboard</a></p>',
  'Hi {{userName}},\n\n{{message}}\n\nDashboard: {{dashboardUrl}}\n\n— {{appName}}',
  'Generic admin message (e.g. notes). Placeholders: userName, appName, message, dashboardUrl'
)
ON CONFLICT (key) DO UPDATE SET
  name = EXCLUDED.name,
  subject = EXCLUDED.subject,
  body_html = EXCLUDED.body_html,
  text_body = EXCLUDED.text_body,
  description = EXCLUDED.description,
  updated_at = now();
