-- Create admins table if missing, then seed one super_admin (run in Supabase SQL Editor).
-- Matches ADMIN_EMAIL and ADMIN_API_KEY in backend .env.

CREATE TABLE IF NOT EXISTS public.admins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL,
  api_key TEXT,
  role TEXT NOT NULL DEFAULT 'viewer' CHECK (role IN ('super_admin', 'admin', 'viewer'))
);

CREATE UNIQUE INDEX IF NOT EXISTS admins_email_key ON public.admins (email);

INSERT INTO public.admins (email, api_key, role)
  VALUES ('contact.awais.ai@gmail.com', '20072002', 'super_admin')
ON CONFLICT (email) DO UPDATE SET
  role = EXCLUDED.role,
  api_key = EXCLUDED.api_key;

-- Log in at /admin/login with the same email and API key as in backend .env.
